# Generated by Django 5.0.4 on 2024-04-28 15:00

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='file_path',
            field=models.ImageField(upload_to=product.models.ProductImage.product_image_path),
        ),
    ]
